# Generated by Django 4.0 on 2021-12-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emid', models.IntegerField()),
                ('emname', models.CharField(max_length=20)),
                ('emsalary', models.IntegerField()),
                ('emadd', models.CharField(max_length=40)),
            ],
        ),
    ]
